#+TITLE: Setup editing
#+DESCRIPTION: Require some editing-specific packages and set up some nice bindings
#+AUTHOR: Maximilian Kuschewski
#+PROPERTY: my-file-type emacs-config-package

* Bootstrap Keys
#+begin_src emacs-lisp
(config/declare-feature-space "e" "Editing" :editing)
#+end_src
* Built-in
Configure built-in functions.
** Keybindings
Repeat the last command.
#+begin_src emacs-lisp
(global-set-key (kbd "C-.") 'repeat)
#+end_src

Copy the current line if there is no active region
#+begin_src emacs-lisp
(global-set-key (kbd "M-w") 'save-region-or-current-line)
#+end_src

Expand the word using the context of killed words/known symbols
#+begin_src emacs-lisp
(global-set-key (kbd "M-/") 'hippie-expand)
#+end_src

Delete whitespace around the point, only leaving one:
#+begin_src emacs-lisp
;; M-SPC is bound to iTerm already
(global-set-key (kbd "H-SPC") 'just-one-space)
#+end_src

Control-h and Meta-h for deleting backwards
#+begin_src emacs-lisp
(define-key key-translation-map [?\C-h] [?\C-?])
(global-set-key (kbd "M-h") 'kill-region-or-backward-word)
#+end_src

Not quite built-in, but defined myself:
#+begin_src emacs-lisp
(global-set-key (kbd "s-c") 'cleanup-buffer)
(config/provide-feature :buffer "c" 'cleanup-buffer)
#+end_src

Join lines more easily
#+begin_src emacs-lisp
;; M-S-6 is awkward
(global-set-key (kbd "s-l") 'join-line)
#+end_src

** Visuals
Highlight matching parentheses when the point is on them.
#+begin_src emacs-lisp
(show-paren-mode 1)
#+end_src
* :use-package yasnippet
** :defer t
** :init
Activate globally it after the init process
#+begin_src emacs-lisp
(add-hook 'after-init-hook #'yas-global-mode)
#+end_src

* :use-package expand-region
** :defer t
** :bind
Every time this key is pressed, expand the region out one step further
#+begin_src emacs-lisp
("s-e" . er/expand-region)
#+end_src
** :init
Provide bindings in the global leader as well.
#+begin_src emacs-lisp
(config/provide-feature :editing
  "e" 'er/expand-region
  "E" (config/hydra hydra/expand-region (:color red)
        "expand-region"
        ("e" er/expand-region "expand")
        ("E" er/expand-region "expand")
        ("c" er/contract-region "contract")
        ("q" nil "quit")))
#+end_src
* :use-package multiple-cursors
** :defer t
** :bind
Most. Awesome. Thing. Ever.
#+begin_src emacs-lisp
("s-d" . mc/mark-next-like-this)
("s-g" . mc/mark-all-like-this)
;; ("C-s-d" . mc/mark-all-dwim)
#+end_src
** :init
Provide bindings in the global leader as well.
#+begin_src emacs-lisp
(config/provide-feature :editing
  "m" (config/hydra hydra/multiple-cursors (:color red)
        "multiple-cursors"
        ("n" mc/mark-next-like-this "mark next")
        ("a" mc/mark-all-like-this "mark all")
        ("q" nil "quit")))
#+end_src

* :use-package browse-kill-ring
** :defer t
** :bind
Look through the kill ring and insert exactly what you want.
#+begin_src emacs-lisp
("C-x C-y" . browse-kill-ring)

#+end_src
** :init
#+begin_src emacs-lisp
(config/provide-feature :editing
  "b" 'browse-kill-ring)
#+end_src
* :use-package undo-tree
** :defer t
** :init
#+begin_src emacs-lisp
(config/provide-feature :editing
  "u" 'undo-tree-visualize)
#+end_src
* Provide it
#+begin_src emacs-lisp
(provide 'setup-editing)
#+end_src
